export const userMessages = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Name length must be from 1 to 100',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_100: 'Password length must be from 6 to 100',
  PASSWORD_MUST_BE_STRONG:
    'Password must be 6 - 100 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_EQUAL_TO_PASSWORD: 'Confirm password must be equal to password',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
  DATE_OF_BIRTH_MUST_BE_IS8601: 'Date of birth must be ISO 8601 date string',
  USER_NOT_FOUND: 'User not found',
  EMAIL_OR_PASSWORD_IS_INCORRECT: 'Email or password is incorrect',
  AUTHORIZATION_HEADER_IS_REQUIRED: 'Authorization header is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  USED_REFRESH_TOKEN_OR_REFRESH_TOKEN_NOT_EXIST: "Used refresh token or refresh token doesn't exist",
  LOGOUT_SUCCESS: 'Logout success',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  EMAIL_VERIFICATION_TOKEN_IS_REQUIRED: 'Email verification token is required',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_VERIFIED_SUCCESS: 'Email verified success',
  REGISTER_SUCCESS: 'Register success',
  LOGIN_SUCCESS: 'Login success',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Resend verify email success',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCCESS: 'Verify forgot password token success',
  INVALID_FORGOT_PASSWORD_TOKEN: 'Invalid forgot password token',
  RESET_PASSWORD_SUCCESS: 'Reset password success',
  GET_ME_SUCCESS: 'Get me success',
  USER_NOT_VERIFIED: 'User not verified',
  BIO_MUST_BE_A_STRING: 'Bio must be a string',
  BIO_LENGTH_MUST_BE_FROM_1_TO_200: 'Bio length must be from 1 to 200',
  LOCATION_LENGTH_MUST_BE_FROM_1_TO_200: 'Location length must be from 1 to 200',
  LOCATION_MUST_BE_A_STRING: 'Location must be a string',
  IMAGE_MUST_BE_A_STRING: 'Image must be a string',
  IMAGE_LENGTH_MUST_BE_FROM_1_TO_400: 'Image length must be from 1 to 400',
  UPDATE_ME_SUCCESS: 'Update me success',
  FOLLOW_SUCCESS: 'Follow success',
  FOLLOW_USER_ID_IS_INVALID: 'Follow user id is invalid',
  ALREADY_FOLLOW_THIS_USER: 'You already follow this user',
  USER_ID_IS_INVALID: 'User id is invalid',
  ALREADY_UNFOLLOW_THIS_USER: 'Already unfollow this user',
  UNFOLLOW_SUCCESS: 'Unfollow success',
  USERNAME_MUST_BE_A_STRING: 'Username must be a string',
  USERNAME_INVALID: 'Username must be a string and contain only letters, numbers and underscores, not only numbers',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  GET_PROFILE_SUCCESS: 'Get profile success',
  OLD_PASSWORD_NOT_MATCHED: 'Old password not matched',
  GMAIL_NOT_VERIFIED: 'Gmail not verified'
} as const
